/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.mycompany.paplicaciones;

import DataTypes.DTActividad;
import DataTypes.DTDepartamento;
import DataTypes.DTSalida;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import main.java.logica.Fabrica;
import main.java.logica.IController;

/**
 *
 * @author capo_
 */
public class AltaSalidaTuristica extends javax.swing.JPanel {

    /**
     * Creates new form AltaActividadTuristica
     */
    public AltaSalidaTuristica() {      initComponents();
        Fabrica fab = Fabrica.getInstance();
        IController I = fab.getIController();
        ArrayList<DTDepartamento> listaDepartamentos = I.getDepartamentos();
        DefaultComboBoxModel modelDepartamentos = new DefaultComboBoxModel();
    for(int i=0;i<listaDepartamentos.size();i++){
        
            modelDepartamentos.addElement(listaDepartamentos.get(i).getNom());
        }
    jComboBoxDepto.setModel(modelDepartamentos);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jTextFieldLugar = new javax.swing.JTextField();
        jTextFieldCapacidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonAlta = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxDepto = new javax.swing.JComboBox<>();
        jComboBoxActividad = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 166, -1, 30));

        jLabel4.setText("Fecha");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 30));

        jLabel5.setText("Hora");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, 30));

        jLabel8.setText("Lugar de Salida");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 30));

        jLabel9.setText("Capacidad");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, 30));

        jLabel10.setText("Fecha de Alta");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 30));

        jTextFieldNombre.setText(" ");
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 171, 465, -1));

        jTextFieldHora.setToolTipText("");
        jTextFieldHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldHoraKeyPressed(evt);
            }
        });
        add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 263, 465, -1));

        jTextFieldLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLugarKeyPressed(evt);
            }
        });
        add(jTextFieldLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 314, 465, -1));

        jTextFieldCapacidad.setText(" ");
        jTextFieldCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCapacidadActionPerformed(evt);
            }
        });
        jTextFieldCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCapacidadKeyPressed(evt);
            }
        });
        add(jTextFieldCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 360, 465, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ALTA SALIDA TURÍSTICA");
        jLabel12.setBorder(new javax.swing.border.MatteBorder(null));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 100));

        jButtonAlta.setText("Registrar Salida");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        add(jButtonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 150, 30));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Departamento");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Actividad");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        jComboBoxDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDeptoActionPerformed(evt);
            }
        });
        add(jComboBoxDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 127, -1, -1));

        jComboBoxActividad.setRequestFocusEnabled(false);
        jComboBoxActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActividadActionPerformed(evt);
            }
        });
        add(jComboBoxActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 127, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 170, -1));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        Fabrica fab = Fabrica.getInstance();
        IController I = fab.getIController();
        
        String defaultPaqueteString="Seleccione un paquete";
        String defaultDepartamentoString="Seleccione un departamento";
        String defaultSalidaString="Seleccione un salida";
        String defaultUsuarioString="Seleccione un usuario";
        String defaultInscripcionString="Seleccione un inscripcion";
        
        String nombre, lugar,hora,depto,actividad;
        Integer dia,mes,anio,diaAlta,mesAlta,anioAlta,capacidad;
        Date fecha,fAlta;
        
        
        depto     = (String)jComboBoxDepto    .getSelectedItem();
        actividad = (String)jComboBoxActividad.getSelectedItem();
        
        nombre=jTextFieldNombre.getText();
        lugar= jTextFieldLugar .getText();
        hora=  jTextFieldHora  .getText();
        
        capacidad=  Integer.valueOf(jTextFieldCapacidad.getText().trim());
        
        fecha = jDateChooser1.getDate();
        
        fAlta = jDateChooser2.getDate();
        
        
        DTSalida dt = new DTSalida(fecha, fAlta,nombre,lugar,hora,capacidad,actividad);
        if (I.salidaExiste(nombre)){
            JOptionPane.showMessageDialog(null, "Ya existe una salida con ese nombre");
        }else{
            if(nombre!=" "){
                I.altaSalida(dt);
            }else{
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un nombre para la salida");
            }

            jTextFieldCapacidad.setText(null);
            jTextFieldNombre   .setText(null);
            jTextFieldLugar    .setText(null);
            jTextFieldHora     .setText(null);
            
            Laboratorio1 lab = Laboratorio1.getInstance();
            lab.actualizar();
        }
        
        
        
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jComboBoxDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDeptoActionPerformed
        jComboBoxActividad.setEnabled(true);
        Fabrica fab = Fabrica.getInstance();
        IController I = fab.getIController();
        String defaultActividadString="Seleccione una actividad";
        
        ArrayList<DTActividad> listaActividades = I.listarActividadesDepartamento((String) jComboBoxDepto.getSelectedItem());
        DefaultComboBoxModel modelActividades = new DefaultComboBoxModel();
        
        modelActividades.addElement(defaultActividadString);
        
        for(int i=0;i<listaActividades.size();i++){
            
                modelActividades.addElement(listaActividades.get(i).getNombre());
        }
    jComboBoxActividad.setModel(modelActividades);
    }//GEN-LAST:event_jComboBoxDeptoActionPerformed

    private void jComboBoxActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActividadActionPerformed

    private void jTextFieldCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCapacidadActionPerformed

    private void jTextFieldCapacidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCapacidadKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextFieldCapacidad.setEditable(false);
        }else{
            jTextFieldCapacidad.setEditable(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCapacidadKeyPressed

    private void jTextFieldLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLugarKeyPressed
                // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLugarKeyPressed

    private void jTextFieldHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHoraKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextFieldHora.setEditable(false);
        }else{
            jTextFieldHora.setEditable(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JComboBox<String> jComboBoxActividad;
    private javax.swing.JComboBox<String> jComboBoxDepto;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCapacidad;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
