package main.java.com.mycompany.paplicaciones;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import DataTypes.DTUsuario;
import main.java.logica.Fabrica;
import main.java.logica.IController;
import main.java.logica.Usuario;

/**
 *
 * @author usuario
 */
public class ConsultaUsuario extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaUsuario
     */
    public ConsultaUsuario() {
        initComponents();
        jLabelnickname.setVisible(false);
        jLabelAltaUsuario.setVisible(true);
        jLabelApellido.setVisible(false);
        jLabelCorreoElectronico.setVisible(false);
        jLabelDescripcionGeneral.setVisible(false);
        jLabelFechNac.setVisible(false);
        jLabelNombre.setVisible(false);
        jLabellink.setVisible(false);
        jLabelnacionalidad.setVisible(false);
        jLabelnickname.setVisible(false);
        jTextFieldnickname.setVisible(false);
        jTextFieldnombre.setVisible(false);
        jTextFieldapellido.setVisible(false);
        jTextFieldcorreoElectrónico.setVisible(false);
        
        
        jLabelDescripcionGeneral.setVisible(false);
        jTextArealDescripcionGeneral.setVisible(false);
        
        jLabellink.setVisible(false);
        jTextFieldlink.setVisible(false);
        jTextFieldnacionalidad.setVisible(false);
        jLabelnacionalidad.setVisible(false);
    
        
        jLabelDia.setVisible(false);
        jLabelMes.setVisible(false);
        jLabelAnio.setVisible(false);
        jTextFieldDia.setVisible(false);
        jTextFieldMes.setVisible(false);
        jTextFieldAnio.setVisible(false);
        
        jLabelActividadesTuristicas.setVisible(false);
        jListctividadesTuristicas.setVisible(false);
        jLabelSalidas.setVisible(false);
        jListSalidas.setVisible(false);
        jLabelSalidasinscriptas.setVisible(false);
        jListSalidasinscriptas.setVisible(false);
        
        jListusuarios.setVisible(true);
        jListusuarios.setAutoscrolls(true);
        
        Fabrica f=Fabrica.getInstance();
        IController I= f.getIController();
        ArrayList<Usuario> usuarios=I.getUsuarios();
        //Crear un objeto DefaultListModel
        DefaultListModel listModel = new DefaultListModel();
        //Recorrer el contenido del ArrayList
        for (int i = 0; i < usuarios.size(); i++) {
            //Añadir cada elemento del ArrayList en el modelo de la lista
            listModel.add(i, usuarios.get(i).getNick());
        }
        //Asociar el modelo de lista al JList
        jListusuarios.setModel(listModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbTuristaProveedor = new javax.swing.JComboBox<>();
        jTextFieldnickname = new javax.swing.JTextField();
        jLabelnickname = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldnombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldapellido = new javax.swing.JTextField();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jTextFieldcorreoElectrónico = new javax.swing.JTextField();
        jLabelFechNac = new javax.swing.JLabel();
        jLabelnacionalidad = new javax.swing.JLabel();
        jTextFieldnacionalidad = new javax.swing.JTextField();
        jLabelDescripcionGeneral = new javax.swing.JLabel();
        jLabellink = new javax.swing.JLabel();
        jTextFieldlink = new javax.swing.JTextField();
        jPanelDescripcionGeneral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArealDescripcionGeneral = new javax.swing.JTextArea();
        jLabelAltaUsuario = new javax.swing.JLabel();
        jLabelDia = new javax.swing.JLabel();
        jTextFieldDia = new javax.swing.JTextField();
        jLabelMes = new javax.swing.JLabel();
        jTextFieldMes = new javax.swing.JTextField();
        jLabelAnio = new javax.swing.JLabel();
        jTextFieldAnio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListctividadesTuristicas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSalidas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListSalidasinscriptas = new javax.swing.JList<>();
        jLabelActividadesTuristicas = new javax.swing.JLabel();
        jLabelSalidas = new javax.swing.JLabel();
        jLabelSalidasinscriptas = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListusuarios = new javax.swing.JList<>();

        cmbTuristaProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Turista", "Proveedor" }));
        cmbTuristaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTuristaProveedorActionPerformed(evt);
            }
        });

        jTextFieldnickname.setText(" ");
        jTextFieldnickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnicknameActionPerformed(evt);
            }
        });

        jLabelnickname.setText("Nickname");

        jLabelNombre.setText("Nombre");

        jTextFieldnombre.setText(" ");

        jLabelApellido.setText("Apellido");

        jTextFieldapellido.setText(" ");

        jLabelCorreoElectronico.setText("Correo Electrónico");

        jTextFieldcorreoElectrónico.setText(" ");

        jLabelFechNac.setText("Fecha de Nacimiento");

        jLabelnacionalidad.setText("Nacionalidad");

        jTextFieldnacionalidad.setText(" ");

        jLabelDescripcionGeneral.setText("Descripción General");

        jLabellink.setText("Link a su sitio web");

        jTextFieldlink.setText(" ");

        javax.swing.GroupLayout jPanelDescripcionGeneralLayout = new javax.swing.GroupLayout(jPanelDescripcionGeneral);
        jPanelDescripcionGeneral.setLayout(jPanelDescripcionGeneralLayout);
        jPanelDescripcionGeneralLayout.setHorizontalGroup(
            jPanelDescripcionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanelDescripcionGeneralLayout.setVerticalGroup(
            jPanelDescripcionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArealDescripcionGeneral.setColumns(20);
        jTextArealDescripcionGeneral.setRows(5);
        jTextArealDescripcionGeneral.setBorder(null);
        jScrollPane1.setViewportView(jTextArealDescripcionGeneral);

        jLabelAltaUsuario.setText("Alta de Usuario");

        jLabelDia.setText("D");

        jTextFieldDia.setText(" ");

        jLabelMes.setText(" M");

        jTextFieldMes.setText(" ");

        jLabelAnio.setText("A");

        jTextFieldAnio.setText(" ");

        jListctividadesTuristicas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListctividadesTuristicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListctividadesTuristicasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListctividadesTuristicas);

        jListSalidas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSalidasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListSalidas);

        jListSalidasinscriptas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSalidasinscriptas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSalidasinscriptasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jListSalidasinscriptas);

        jLabelActividadesTuristicas.setText("Actividades Turisticas");

        jLabelSalidas.setText("Salidas");

        jLabelSalidasinscriptas.setText("Inscripciones");

        jListusuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListusuariosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListusuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabellink, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldlink, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelFechNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelCorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelDescripcionGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabelApellido))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabelDia)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabelMes)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldMes, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabelAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jTextFieldcorreoElectrónico, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFieldnickname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldapellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabelnickname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmbTuristaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelDescripcionGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelActividadesTuristicas)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelSalidas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalidasinscriptas)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldnickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelnickname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelApellido)
                                    .addComponent(jTextFieldapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldcorreoElectrónico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCorreoElectronico)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbTuristaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFechNac)
                            .addComponent(jLabelDia)
                            .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMes)
                            .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnio)
                            .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnacionalidad)
                            .addComponent(jTextFieldnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelDescripcionGeneral))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabellink)))
                    .addComponent(jPanelDescripcionGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelActividadesTuristicas)
                        .addComponent(jLabelSalidas))
                    .addComponent(jLabelSalidasinscriptas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTuristaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTuristaProveedorActionPerformed
        String opcion=(String)cmbTuristaProveedor.getSelectedItem();
        if(opcion.equals("Turista")){
            jLabelnickname.setVisible(true);
            jLabelAltaUsuario.setVisible(true);
            jLabelApellido.setVisible(true);
            jLabelCorreoElectronico.setVisible(true);
            jLabelDescripcionGeneral.setVisible(false);
            jLabelFechNac.setVisible(true);
            jLabelNombre.setVisible(true);
            jLabellink.setVisible(false);
            jLabelnacionalidad.setVisible(true);
            jLabelnickname.setVisible(true);
            jTextFieldnickname.setVisible(true);
            jTextFieldnombre.setVisible(true);
            jTextFieldapellido.setVisible(true);
            jTextFieldcorreoElectrónico.setVisible(true);

            jLabelDescripcionGeneral.setVisible(false);
            jTextArealDescripcionGeneral.setVisible(false);
            jPanelDescripcionGeneral.setVisible(true);
            jLabellink.setVisible(false);
            jTextFieldlink.setVisible(false);
            jTextFieldnacionalidad.setVisible(true);
            jLabelnacionalidad.setVisible(true);
          

            jLabelDia.setVisible(true);
            jLabelMes.setVisible(true);
            jLabelAnio.setVisible(true);
            jTextFieldDia.setVisible(true);
            jTextFieldMes.setVisible(true);
            jTextFieldAnio.setVisible(true);
            
            jLabelActividadesTuristicas.setVisible(false);
            jListctividadesTuristicas.setVisible(false);
            jLabelSalidas.setVisible(false);
            jListSalidas.setVisible(false);
            jLabelSalidasinscriptas.setVisible(true);
            jListSalidasinscriptas.setVisible(true);
            
            jListusuarios.setVisible(true);
            
            
            jTextFieldnickname.setText("");
            jTextFieldnombre.setText("");
            jTextFieldapellido.setText("");
            jTextFieldcorreoElectrónico.setText("");
            jTextFieldnacionalidad.setText("");
            jTextFieldDia.setText("");
            jTextFieldMes.setText("");
            jTextFieldAnio.setText("");
        }
        if(opcion.equals("Proveedor")){
            jLabelnickname.setVisible(true);
            jLabelAltaUsuario.setVisible(true);
            jLabelApellido.setVisible(true);
            jLabelCorreoElectronico.setVisible(true);
            jLabelDescripcionGeneral.setVisible(true);
            jLabelFechNac.setVisible(true);
            jLabelNombre.setVisible(true);
            jLabellink.setVisible(true);
            jLabelnacionalidad.setVisible(false);
            jLabelnickname.setVisible(true);
            jTextFieldnickname.setVisible(true);
            jTextFieldnombre.setVisible(true);
            jTextFieldapellido.setVisible(true);
            jTextFieldcorreoElectrónico.setVisible(true);

            jLabelDescripcionGeneral.setVisible(true);
            jTextArealDescripcionGeneral.setVisible(true);
            jPanelDescripcionGeneral.setVisible(false);
            jTextArealDescripcionGeneral.setAutoscrolls(true);
            jLabellink.setVisible(true);
            jTextFieldlink.setVisible(true);
            jTextFieldnacionalidad.setVisible(false);
            jLabelnacionalidad.setVisible(false);
          

            jLabelDia.setVisible(true);
            jLabelMes.setVisible(true);
            jLabelAnio.setVisible(true);
            jTextFieldDia.setVisible(true);
            jTextFieldMes.setVisible(true);
            jTextFieldAnio.setVisible(true);
            
            jLabelActividadesTuristicas.setVisible(true);
            jListctividadesTuristicas.setVisible(true);
            jLabelSalidas.setVisible(true);
            jListSalidas.setVisible(true);
            jLabelSalidasinscriptas.setVisible(false);
            jListSalidasinscriptas.setVisible(false);
            
            jListusuarios.setVisible(true);
            
             jTextFieldnickname.setText("");
            jTextFieldnombre.setText("");
            jTextFieldapellido.setText("");
            jTextFieldcorreoElectrónico.setText("");
            jTextFieldnacionalidad.setText("");
            jTextFieldDia.setText("");
            jTextFieldMes.setText("");
            jTextFieldAnio.setText("");
            
        }
        if(opcion.equals("Usuario")){
            jLabelnickname.setVisible(false);
            jLabelAltaUsuario.setVisible(true);
            jLabelApellido.setVisible(false);
            jLabelCorreoElectronico.setVisible(false);
            jLabelDescripcionGeneral.setVisible(false);
            jLabelFechNac.setVisible(false);
            jLabelNombre.setVisible(false);
            jLabellink.setVisible(false);
            jLabelnacionalidad.setVisible(false);
            jLabelnickname.setVisible(false);
            jTextFieldnickname.setVisible(false);
            jTextFieldnombre.setVisible(false);
            jTextFieldapellido.setVisible(false);
            jTextFieldcorreoElectrónico.setVisible(false);
            jLabelDescripcionGeneral.setVisible(false);
            jTextArealDescripcionGeneral.setVisible(false);
            jPanelDescripcionGeneral.setVisible(true);
            jLabellink.setVisible(false);
            jTextFieldlink.setVisible(false);
            jTextFieldnacionalidad.setVisible(false);
            jLabelnacionalidad.setVisible(false);
         

            jLabelDia.setVisible(false);
            jLabelMes.setVisible(false);
            jLabelAnio.setVisible(false);
            jTextFieldDia.setVisible(false);
            jTextFieldMes.setVisible(false);
            jTextFieldAnio.setVisible(false);
            
            jLabelActividadesTuristicas.setVisible(false);
            jListctividadesTuristicas.setVisible(false);
            jLabelSalidas.setVisible(false);
            jListSalidas.setVisible(false);
            jLabelSalidasinscriptas.setVisible(false);
            jListSalidasinscriptas.setVisible(false);
            
            jListusuarios.setVisible(true);
        }
    }//GEN-LAST:event_cmbTuristaProveedorActionPerformed

    private void jTextFieldnicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnicknameActionPerformed
        
    }//GEN-LAST:event_jTextFieldnicknameActionPerformed

    private void jListctividadesTuristicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListctividadesTuristicasMouseClicked
        AltaActividadTuristica contenido=new AltaActividadTuristica();
        contenido.setSize(800,600);
        contenido.setLocation(0,0);
        JDialog contenedor=new JDialog();
        contenedor.setSize(800,600);
        contenedor.setLocation(0,0);
        contenedor.add(contenido,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        contenedor.setVisible(true);
                
    }//GEN-LAST:event_jListctividadesTuristicasMouseClicked

    private void jListSalidasinscriptasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSalidasinscriptasMouseClicked
        AltaSalidaTuristica contenido=new AltaSalidaTuristica();
        contenido.setSize(800,600);
        contenido.setLocation(0,0);
        JDialog contenedor=new JDialog();
        contenedor.setSize(800,600);
        contenedor.setLocation(0,0);
        contenedor.add(contenido,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        contenedor.setVisible(true);
    }//GEN-LAST:event_jListSalidasinscriptasMouseClicked

    private void jListusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListusuariosMouseClicked
       
            
        String nickname=jListusuarios.getSelectedValue();
        Fabrica f=Fabrica.getInstance();
        IController I= f.getIController();
        DTUsuario dt=I.getUsuario(nickname);
        String opcion=(String)cmbTuristaProveedor.getSelectedItem();
        if(dt.getEsTurista()==1){    
            cmbTuristaProveedor.setSelectedIndex(1); 
            jTextFieldnickname.setText(dt.getNick().trim());
            jTextFieldnombre.setText(dt.getNom().trim());
            jTextFieldapellido.setText(dt.getApe().trim());
            jTextFieldcorreoElectrónico.setText(dt.getMail().trim());
            
            int dia=dt.getFnac().getDate();
            String d=Integer.toString(dia).trim();
            jTextFieldDia.setText(d);
            
            int mes=dt.getFnac().getMonth();
            String m=Integer.toString(mes).trim();
            jTextFieldMes.setText(m);
            
            int anio=dt.getFnac().getYear();
            String a=Integer.toString(anio).trim();
            jTextFieldAnio.setText(a);
            
            jTextFieldnacionalidad.setText(dt.getNacionalidad().trim());
            
            ArrayList<String> salidas = new ArrayList();
            salidas = I.listarsalidasinscriptasTurista(nickname);;
            salidas.add("montevido");
            salidas.add("maldonado");
            //Crear un objeto DefaultListModel
            DefaultListModel listModel = new DefaultListModel();
            //Recorrer el contenido del ArrayList
            for (int i = 0; i < salidas.size(); i++) {
                //Añadir cada elemento del ArrayList en el modelo de la lista
                listModel.add(i, salidas.get(i));
            }
            //Asociar el modelo de lista al JList
            jListSalidasinscriptas.setModel(listModel);
            

        }
        if(dt.getEsTurista()==0){    
            cmbTuristaProveedor.setSelectedIndex(2);
            jTextFieldnickname.setText(dt.getNick().trim());
            jTextFieldnombre.setText(dt.getNom().trim());
            jTextFieldapellido.setText(dt.getApe().trim());
            jTextFieldcorreoElectrónico.setText(dt.getMail().trim());
            
            int dia=dt.getFnac().getDate();
            String d=Integer.toString(dia).trim();
            jTextFieldDia.setText(d);
            
            int mes=dt.getFnac().getMonth();
            String m=Integer.toString(mes).trim();
            jTextFieldMes.setText(m);
            
            int anio=dt.getFnac().getYear();
            String a=Integer.toString(anio).trim();
            jTextFieldAnio.setText(a);
            
            jTextArealDescripcionGeneral.setText(dt.getDescripcion().trim());
            jTextFieldlink.setText(dt.getWeb().trim());
            
            ArrayList<String> actividades = new ArrayList();
            ArrayList<String> salidas = new ArrayList();
            actividades=I.listarActividadesProveedor(nickname);
            salidas = I.listarsalidasProveedor(nickname);
            
            actividades.add("correr");
            actividades.add("saltar");
            salidas.add("*");
            salidas.add("montevido");
            salidas.add("maldonado");
            salidas.add("*");
            salidas.add("canelones");
            //Crear un objeto DefaultListModel
            DefaultListModel listModelsalidas = new DefaultListModel();
            DefaultListModel listModelActividades = new DefaultListModel();
            //Recorrer el contenido del ArrayList
            int cont=0;
            for (int i = 0; i < salidas.size(); i++) {
                if( salidas.get(i).equals("*")){
                    listModelActividades.add(i, actividades.get(cont));
                     listModelsalidas.add(i, "\n");
                    cont++;
                }
                else{
                    listModelActividades.add(i,"\n" );
                     listModelsalidas.add(i, salidas.get(i));
                }
                
               
            }
            //Asociar el modelo de lista al JList
            jListSalidas.setModel(listModelsalidas);
            jListctividadesTuristicas.setModel(listModelActividades);
        }
    }//GEN-LAST:event_jListusuariosMouseClicked

    private void jListSalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSalidasMouseClicked
        AltaSalidaTuristica contenido=new AltaSalidaTuristica();
        contenido.setSize(800,600);
        contenido.setLocation(0,0);
        JDialog contenedor=new JDialog();
        contenedor.setSize(800,600);
        contenedor.setLocation(0,0);
        contenedor.add(contenido,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        contenedor.setVisible(true);
    }//GEN-LAST:event_jListSalidasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTuristaProveedor;
    private javax.swing.JLabel jLabelActividadesTuristicas;
    private javax.swing.JLabel jLabelAltaUsuario;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JLabel jLabelDescripcionGeneral;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelFechNac;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalidas;
    private javax.swing.JLabel jLabelSalidasinscriptas;
    private javax.swing.JLabel jLabellink;
    private javax.swing.JLabel jLabelnacionalidad;
    private javax.swing.JLabel jLabelnickname;
    private javax.swing.JList<String> jListSalidas;
    private javax.swing.JList<String> jListSalidasinscriptas;
    private javax.swing.JList<String> jListctividadesTuristicas;
    private javax.swing.JList<String> jListusuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDescripcionGeneral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArealDescripcionGeneral;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JTextField jTextFieldMes;
    private javax.swing.JTextField jTextFieldapellido;
    private javax.swing.JTextField jTextFieldcorreoElectrónico;
    private javax.swing.JTextField jTextFieldlink;
    private javax.swing.JTextField jTextFieldnacionalidad;
    private javax.swing.JTextField jTextFieldnickname;
    private javax.swing.JTextField jTextFieldnombre;
    // End of variables declaration//GEN-END:variables
}
